import {
  FaUmbrellaBeach,
  FaBicycle,
  FaBook,
  FaCampground,
  FaCar,
  FaUtensils,
  FaCompactDisc,
  FaSwimmer,
  FaGift,
  FaFish,
  FaGamepad,
  FaPalette,
  FaHockeyPuck,
  FaFilm,
  FaLandmark,
  FaMusic,
  FaLeaf,
  FaGlassMartiniAlt,
  FaShip,
  FaShoppingCart,
  FaHeart,
  FaMapMarkerAlt,
  FaTv,
  FaPrayingHands,
  FaMedal,
  FaCamera,
  FaPlay,
} from 'react-icons/fa';

export const interestIcons = {
  'Lying on the beach': { icon: FaUmbrellaBeach, color: 'bg-lime-500' },
  Biking: { icon: FaBicycle, color: 'bg-orange-500' },
  'Reading books': { icon: FaBook, color: 'bg-fuchsia-900' },
  Camping: { icon: FaCampground, color: 'bg-emerald-500' },
  Cars: { icon: FaCar, color: 'bg-red-500' },
  Cooking: { icon: FaUtensils, color: 'bg-amber-400' },
  Dancing: { icon: FaCompactDisc, color: 'bg-violet-900' },
  Diving: { icon: FaSwimmer, color: 'bg-blue-500' },
  Fashion: { icon: FaGift, color: 'bg-purple-400' },
  'Fishing & Hunting': { icon: FaFish, color: 'bg-indigo-700' },
  Games: { icon: FaGamepad, color: 'bg-lime-600' },
  'Hobbies & Crafts': { icon: FaPalette, color: 'bg-rose-400' },
  Hockey: { icon: FaHockeyPuck, color: 'bg-teal-500' },
  Movies: { icon: FaFilm, color: 'bg-cyan-800' },
  'Museums & Art': { icon: FaLandmark, color: 'bg-amber-400' },
  'Music & Concerts': { icon: FaMusic, color: 'bg-sky-500' },
  Nature: { icon: FaLeaf, color: 'bg-emerald-500' },
  'Party & Night Clubs': { icon: FaGlassMartiniAlt, color: 'bg-red-500' },
  Sailing: { icon: FaShip, color: 'bg-orange-300' },
  Shopping: { icon: FaShoppingCart, color: 'bg-sky-300' },
  Sports: { icon: FaMedal, color: 'bg-lime-400' },
  Travelling: { icon: FaMapMarkerAlt, color: 'bg-blue-600' },
  'Watching TV': { icon: FaTv, color: 'bg-orange-500' },
  'Meditation & Yoga': { icon: FaPrayingHands, color: 'bg-slate-300' },
  // Common aliases from older seeded data
  Reading: { icon: FaBook, color: 'bg-fuchsia-900' },
  Music: { icon: FaMusic, color: 'bg-sky-500' },
  Photography: { icon: FaCamera, color: 'bg-gray-500' },
  Fitness: { icon: FaHeart, color: 'bg-teal-500' },
};

export const defaultInterestIcon = { icon: FaHeart, color: 'bg-teal-500' };
export const profileFallbackInterestIcon = { icon: FaHeart, color: 'bg-blue-500' };
export const profilePageFallbackInterestIcon = { icon: FaPlay, color: 'bg-teal-500' };
